name: Compilador de APK en la Nube

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  build:
    name: Ensamblando la APK
    runs-on: ubuntu-latest

    steps:
    - name: Clonando el codigo
      uses: actions/checkout@v4

    - name: Preparando el motor Android
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Configurando Gradle y Compilando
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.4'
        arguments: assembleDebug

    - name: Guardando APK Final
      uses: actions/upload-artifact@v4
      with:
        name: PhoenixBridge-App
        path: app/build/outputs/apk/debug/app-debug.apk

